### ISSUE TITLE
RPC calls to running PseudoNode instance

### ISSUE THREAD

**Issue by suchdatums** [basil00/PseudoNode#5]
Is there is no way to query PseudoNode (and therefore query connected peers) for a specific block/header/tx?

How can this be most easily implemented?  This project is _so_ close!

**Comment by basil00** [comment]
No, this project was originally written for fun and the original implementation was not very good.  I made some effort to improve it some time ago, but then there was not so much interest so it is left "as is".  It is a shame since it provides a very lightweight method for "joining" the network, which can have some useful applications.

So, the current implementation is WYSIWYG, and any new features you'll need to add yourself.
